class Autogenerated {
  Data? data;
  String? message;
  String? accessToken;
  bool? status;

  Autogenerated({this.data, this.message, this.accessToken, this.status});

  Autogenerated.fromJson(Map<String, dynamic> json) {
    data = json['data'] != null ? new Data.fromJson(json['data']) : null;
    message = json['message'];
    accessToken = json['access_token'];
    status = json['status'];
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    if (this.data != null) {
      data['data'] = this.data!.toJson();
    }
    data['message'] = this.message;
    data['access_token'] = this.accessToken;
    data['status'] = this.status;
    return data;
  }
}

class Data {
  String? fName;
  String? lName;
  String? paymentMethod;
  String? email;
  String? deviceToken;
  String? phone;
  String? status;
  String? role;
  int? id;
  String? stripeCustomerId;

  Data(
      {this.fName,
        this.lName,
        this.paymentMethod,
        this.email,
        this.deviceToken,
        this.phone,
        this.status,
        this.role,
        this.id,
        this.stripeCustomerId});

  Data.fromJson(Map<String, dynamic> json) {
    fName = json['f_name'];
    lName = json['l_name'];
    paymentMethod = json['payment_method'];
    email = json['email'];
    deviceToken = json['device_token'];
    phone = json['phone'];
    status = json['status'];
    role = json['role'];
    id = json['id'];
    stripeCustomerId = json['stripe_customer_id'];
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    data['f_name'] = this.fName;
    data['l_name'] = this.lName;
    data['payment_method'] = this.paymentMethod;
    data['email'] = this.email;
    data['device_token'] = this.deviceToken;
    data['phone'] = this.phone;
    data['status'] = this.status;
    data['role'] = this.role;
    data['id'] = this.id;
    data['stripe_customer_id'] = this.stripeCustomerId;
    return data;
  }
}