

import 'package:get/get.dart';
import 'package:loginsigi/modals/signupmodal.dart';
class signUpApi extends GetConnect{


  Future<Autogenerated> signUp ({
    required String phone,required String fname,required String lname,required String email,})async{
    var response=await httpClient.post("https://bolt.devglocal.com/api/user/signup",

      body: {
        "phone": phone,
        "first_name": fname,
        "last_name": lname,
        "email": email,
        "device_token": "deviceToken",
      }
    );
    if(response.hasError){
      return Future.error(response.statusText!);
    }else{

      Autogenerated model=Autogenerated.fromJson(response.body);
      return model;
    }
  }

}